### ISSUE TITLE
Add autoscroll to today 'dayItem' with toolbar action

### ISSUE THREAD

**Issue by pawegio** [elpassion/el-space-android#23]
I am missing a toolbar action (available e.g. in Google Calendar app) that allows me to smoothly autoscroll to current dayItem on `RecyclerView`.

**Comment by jozzi05** [comment]
What will happen when you are on previous month?

**Comment by pawegio** [comment]
It should change month to current and then perform scroll.

**Comment by jozzi05** [comment]
:+1:

**Comment by marcinsus** [comment]
👍

**Comment by jozzi05** [comment]
There is a bug.
1. Press scroll to today icon
2. Change month to previous
3. Previous month is scrolled down
